name: 更新文章索引

permissions:
  contents: write

on:
  push:
    paths:
      - 'blog/posts/*.md'
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 设置 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 生成文章索引
        run: |
          cd Blog/posts  # 修改这里，使用正确的路径
          echo "[" > index.json
          find . -maxdepth 1 -name "*.md" | sort -r | sed 's/\.\///' | sed 's/$/",/' | sed 's/^/"/' | sed '$s/,$//' >> index.json
          echo "]" >> index.json

      - name: 提交更新的索引文件
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Blog/posts/index.json  # 修改这里，使用正确的路径
          git commit -m "自动更新文章索引" || echo "没有变更"
          git push