name: 更新文章索引和目录结构

permissions:
  contents: write

on:
  push:
    paths:
      - 'Blog/posts/**/*.md'
  workflow_dispatch:

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 设置 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: 生成文章索引
        run: |
          cd Blog/posts
          echo "[" > index.json
          find . -type f -name "*.md" | sort -r | sed 's/\.\///' | sed 's/$/",/' | sed 's/^/"/' | sed '$s/,$//' >> index.json
          echo "]" >> index.json

      - name: 生成目录结构
        run: |
          cd Blog
          echo "{\"directories\":[" > directory-structure.json
          find posts -type d | grep -v "^posts$" | sed 's/posts\///' | sed '/^$/d' | awk '{print "{\"name\":\"" $0 "\",\"path\":\"" $0 "\"}"}' | paste -sd "," >> directory-structure.json
          echo "]}" >> directory-structure.json

      - name: 提交更新的文件
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Blog/posts/index.json Blog/directory-structure.json
          git commit -m "自动更新文章索引和目录结构" || echo "没有变更"
          git push